{{--@include('layout.header_sell')--}}
@extends('layout.header_sell')
@section('sell-index')


            <h3>b</h3>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            v
            v
            v
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>
            <h3>a</h3>
            <h2>hshs</h2>
            <br>


@endsection
